#!/bin/bash -e

install_tools() {
    git clone https://github.com/michaelbruce/tools $HOME/tools
    . $HOME/tools/install
}

install_arch_configuration() {
    mkdir -p $HOME/code
    git clone \
        https://github.com/michaelbruce/arch-configuration \
        $HOME/code/arch-configuration
    [ -L $HOME/.fluxbox ] && unlink $HOME/.fluxbox
    ln -sfv $HOME/code/arch-configuration/fluxbox-configuration $HOME/.fluxbox
}

disable_psmouse_driver() {
  ln -s $HOME/arch-configuration/modprobe.conf /etc/modprobe.d/modprobe.conf
}

main() {
    # install_tools
    # install_arch_configuration
    disable_psmouse_driver
}

main
