#!/bin/bash -e

install_toolkit() {
    git clone https://github.com/mikepjb/toolkit $HOME/toolkit
    . $HOME/toolkit/install
}

install_bspwm() {
    git clone https://github.com/Javyre/bspwm $HOME/src/bspwm
    cd !$
    make && make install
}

install_sysconf() {
    mkdir -p $HOME/src
    git clone \
        https://github.com/mikepjb/sysconf \
        $HOME/src/sysconf
    [ -L $HOME/.config ] && unlink $HOME/.config
    [ -d $HOME/.config ] && rm $HOME/.config
    ln -sfv $HOME/src/sysconf/config $HOME/.config
    mkdir -p ~/Pictures/backgrounds
    ln -s $HOME/src/sysconf/wallpaper.jpg $HOME/Pictures/backgrounds/wallpaper.jpg
}

main() {
  install_toolkit
  install_sysconf
}

main
