#! /bin/sh

sxhkd &
compton &

ponymix set-volume 20

feh --bg-fill ~/Pictures/backgrounds/wallpaper.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config border_radius        4
bspc config window_gap          12

# super + mouse 2 moves the window
bspc config pointer_modifier mod4
bspc config pointer_action1 move

bspc config split_ratio          0.40
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*" split_dir=south
bspc rule -a Firefox split_dir=east
bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled split_dir=west
bspc rule -a xterm split_dir=west
bspc rule -a mplayer2 state=floating
bspc rule -a Peek state=floating

