#!/bin/sh
#
# fluxbox startup-script:

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
ponymix unmute
ponymix set-volume 80
xflux -l 51.7620 -g 0.2280 -k 4800 #with Hatfield latlong
fbsetbg -f ~/Pictures/backgrounds/wallpaper.jpg
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Disable screen timeouts
xset -dpms
xset s off
xset s noblank

#exec fluxbox &
compton -b

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox

#sleep 5
#{
#   # Applications you want to run after fluxbox has started
#   # MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN & AT THE END.
#   # ipager &
#   # gkrellm2 &
#} &
# or if you want to keep a log:
# exec fluxbox -log "/home/hades/.fluxbox/log"
